export const userInterests = [
    'programming',
    'sports',
    'reading',
    'music',
    'traveling',
    'drawing',
    'gardening',
    'photography',
    'writing',
    'volunteering',
    'cooking',
    'cycling',
    'playing computer games',
    'meditation',
    'learning languages',
    'podcasting',
    'designing',
    'knitting',
    'hanging out with friends',
    'hiking',
    'yoga',
    'rock climbing',
    'painting',
    'watching movies',
    'DIY projects',
    'birdwatching',
    'surfing',
    'astronomy',
    'board games',
    'fashion',
    'creative writing',
    'calligraphy',
    'collecting',
    'home brewing',
    'martial arts',
    'scuba diving',
    'playing musical instruments',
    'food tasting/foodie culture',
    'interior design',
    'sustainable living/zero waste practices'
];
