export const userInterests = [
    'programming',
    'sports',
    'reading',
    'music',
    'traveling',
    'drawing',
    'gardening',
    'photography',
    'writing',
    'volunteering',
    'cooking',
    'cycling',
    'games',
    'meditation',
    'languages',
    'podcasting',
    'designing',
    'knitting',
    'hanging out',
    'hiking',
    'yoga',
    'climbing',
    'painting',
    'watching TV',
    'DIY',
    'birdwatching',
    'surfing',
    'astronomy',
    'board games',
    'fashion',
    'calligraphy',
    'collecting',
    'arts',
    'scuba diving',
    'music',
    'design',
];
