query UserConnection($limit: Int, $nextPageCursor: Int) {
    userConnection(limit: $limit, nextPageCursor: $nextPageCursor) {
        age
        bio
        email
        fullName
        gender
        id
        imgURL
        interests
        isAdmin
        location
        password
        socials {
            facebook
            instagram
            twitter
        }
    }
}
